spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/halloween}
    username: ${DATABASE_USERNAME:halloween}
    password: ${DATABASE_PASSWORD:halloween}

  liquibase:
    enabled: true
    change-log: classpath*:/changelog.sql
    database-change-log-table: liquibase_change_log
    database-change-log-lock-table: liquibase_change_log_lock

  discord:
    token: ${DISCORD_TOKEN}

  game:
    log: 1034036007294734336
    channels:
      - 683633975842963456
      - 693712564588380200


---

spring:
  config:
    activate:
      on-profile: development

  game:
    log: 1033813497076785154
    channels:
      - 1033814267994058872
      - 1034026484857319484
